// 解决页面模板中的示例mutation报错
export const DEMO_MUTATION = 'DEMO_MUTATION';

// 设置用户信息
export const SET_USER_INFO = 'SET_USER_INFO';

// 设置异步路由
export const SET_ASYNC_ROUTES = 'SET_ASYNC_ROUTES';

export const SET_ASYNC_MENUS = 'SET_ASYNC_MENUS';

export const ADD_CACHE_ROUTE = 'ADD_CACHE_ROUTE';

export const SET_ELEMENT_PERMISSIONS = 'SET_ELEMENT_PERMISSIONS';

export const TOGGLE_MENU_COLLAPSE = 'TOGGLE_MENU_COLLAPSE';

// 监测
// 设置事件监测表单
export const SET_MONITOR_CREATE_FORM = 'SET_MONITOR_CREATE_FORM';
// 重置事件监测表单
export const RESET_MONITOR_CREATE_FORM = 'RESET_MONITOR_CREATE_FORM';
// 设置监测任务类型
export const SET_MONITOR_CREATE_FORM_TYPE = 'SET_MONITOR_CREATE_FORM_TYPE';
// 设置监测任务基础信息
export const SET_MONITOR_CREATE_FORM_TASK = 'SET_MONITOR_CREATE_FORM_TASK';
// 设置监测任务预警信息
export const SET_MONITOR_CREATE_FORM_EARLY_WARN = 'SET_MONITOR_CREATE_FORM_EARLY_WARN';

// 文章操作
export const SET_SELECTED_ARTICLES = 'SET_SELECTED_ARTICLES';
export const SET_RECEIVERS_DIALOG_VISIBLE = 'SET_RECEIVERS_DIALOG_VISIBLE';
export const SET_REPORT_CLIP_SELECT_DIALOG_VISIBLE = 'SET_REPORT_CLIP_SELECT_DIALOG_VISIBLE';
